# Generated by Django 3.2.25 on 2024-04-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekranimages',
            name='name',
            field=models.CharField(default='Unnamed', max_length=50),
            preserve_default=False,
        ),
    ]
