# Generated by Django 5.0.6 on 2024-06-04 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ekranimages_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='article_images/')),
            ],
            options={
                'verbose_name': 'Article Image',
                'verbose_name_plural': 'Article Images',
            },
        ),
        migrations.RemoveField(
            model_name='articlefacultet',
            name='author',
        ),
        migrations.RemoveField(
            model_name='articlefacultet',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryFacultet',
        ),
        migrations.AlterModelOptions(
            name='articleelon',
            options={'ordering': ['-id'], 'verbose_name': 'Elon', 'verbose_name_plural': 'Elonlar'},
        ),
        migrations.AlterModelOptions(
            name='articlenews',
            options={'ordering': ['-id'], 'verbose_name': 'Maqola', 'verbose_name_plural': 'Maqolalar'},
        ),
        migrations.AlterModelOptions(
            name='categoryelon',
            options={'verbose_name': 'Elonlar Kategoryasi', 'verbose_name_plural': 'Elonlar Kategoryasi'},
        ),
        migrations.AlterModelOptions(
            name='categorynews',
            options={'verbose_name': 'Maqolalar Kategoryasi', 'verbose_name_plural': 'Maqolalar Kategoryasi'},
        ),
        migrations.AddField(
            model_name='articleimage',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.articlenews'),
        ),
        migrations.DeleteModel(
            name='ArticleFacultet',
        ),
    ]
