# Generated by Django 5.0.6 on 2024-06-04 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_articleimage_remove_articlefacultet_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImageElon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='article_images/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.articleelon')),
            ],
            options={
                'verbose_name': 'Elon rasmi',
                'verbose_name_plural': 'Elon rasmlari',
            },
        ),
    ]
