# Generated by Django 5.0.6 on 2024-06-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_articleimageelon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimageelon',
            name='article',
        ),
        migrations.AddField(
            model_name='articleelon',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Photos/Yangiliklar/'),
        ),
        migrations.AddField(
            model_name='articleelon',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Photos/Yangiliklar/'),
        ),
        migrations.AddField(
            model_name='articleelon',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Photos/Yangiliklar/'),
        ),
        migrations.AddField(
            model_name='articlenews',
            name='img1',
            field=models.ImageField(blank=True, upload_to='Photos/Yangiliklar/'),
        ),
        migrations.AddField(
            model_name='articlenews',
            name='img2',
            field=models.ImageField(blank=True, upload_to='Photos/Yangiliklar/'),
        ),
        migrations.AddField(
            model_name='articlenews',
            name='img3',
            field=models.ImageField(blank=True, upload_to='Photos/Yangiliklar/'),
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
        migrations.DeleteModel(
            name='ArticleImageElon',
        ),
    ]
