# Generated by Django 5.0.6 on 2024-06-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_articleimageelon_article_articleelon_img1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleelon',
            name='img1',
            field=models.ImageField(blank=True, default=True, upload_to='Photos/Yangiliklar/'),
        ),
        migrations.AlterField(
            model_name='articleelon',
            name='img2',
            field=models.ImageField(blank=True, default=True, upload_to='Photos/Yangiliklar/'),
        ),
        migrations.AlterField(
            model_name='articleelon',
            name='img3',
            field=models.ImageField(blank=True, default=True, upload_to='Photos/Yangiliklar/'),
        ),
        migrations.AlterField(
            model_name='articlenews',
            name='img1',
            field=models.ImageField(blank=True, default=True, upload_to='Photos/Yangiliklar/'),
        ),
        migrations.AlterField(
            model_name='articlenews',
            name='img2',
            field=models.ImageField(blank=True, default=True, upload_to='Photos/Yangiliklar/'),
        ),
        migrations.AlterField(
            model_name='articlenews',
            name='img3',
            field=models.ImageField(blank=True, default=True, upload_to='Photos/Yangiliklar/'),
        ),
    ]
